console.log('Ini adalah fungsi pertama')
console.log('Ini adalah fungsi pertama')
console.log('Ini adalah fungsi pertama')
console.log('Ini adalah fungsi pertama')
console.log('Ini adalah fungsi pertama')
